---
kind: pipeline
name: default-s390x

platform:
  os: linux
  arch: amd64

node:
  arch: s390x

steps:

- name: build
  pull: default
  image: rancher/dapper:v0.5.8
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock

- name: publish-tagged-image
  image: rancher/drone-images:docker-s390x
  volumes:
    - name: socket
      path: /var/run/docker.sock
  settings:
    build_args:
    - ARCH=s390x
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password_thomasferrandiz_dev
    repo: thomasferrandiz/longhornonz-longhorn-share-manager
    tag: "${DRONE_TAG}-s390x"
    username:
      from_secret: docker_username_thomasferrandiz_dev
  when:
    event:
    - tag

volumes:
- name: socket
  host:
    path: /var/run/docker.sock